### ISSUE TITLE
Doesn't cleanup extra files

### ISSUE THREAD

**Issue by TingPing** [flathub/com.github.lainsce.notejot#1]
All of the libs you build install unused files that should be cleaned up. The `granite` module for example does but `json-glib` isn't. Look in the build directory to see what is there but commonly `/includes`, `/lib/pkgconfig`, `*.la`, etc.

**Comment by lainsce** [comment]
Will do. This only affects the json-glib part, correct?

**Comment by TingPing** [comment]
libgee, json-glib, gtksourceview. Everything installs unused files basically.

**Comment by lainsce** [comment]
I see. Will research which files to remove and do an update to this repo.

**Comment by lainsce** [comment]
There, now it should cleanup every unused file.

**Comment by nedrichards** [comment]
It may do that, but the build failed. Copying here since the github feedback link is currently broken: https://flathub.org/builds/#/builders/1/builds/2217

> Failed to download sources: module notejot: Wrong sha256 checksum for 1.3.8.zip, expected a18539f39415bf102c55cdc4c5bf24a0ecd27e5e808355d3cc7f74205a1c7bd7, was e6663d1e31f4a25ca049dfa10ab10aec1eda0eeee5f00e1bb75f064a695d2c2c

**Comment by lainsce** [comment]
There, I updated the sha256 checksum.
