### ISSUE TITLE
Bad permission

### ISSUE THREAD

**Issue by TingPing** [flathub/com.github.lainsce.notejot#2]
`        "--filesystem=~/.cache/com.github.lainsce.notejot/saved_notes.json:rw",`

This is broken since if it doesn't exist in the host it will fail to launch.

But instead of being fixed it should be removed, Flatpaks are self contained and shouldn't be storing configuration outside of its directory.

**Comment by lainsce** [comment]
This file is created by Notejot at launch, and without it being read/write, or even there in the flatpak, the app will indeed fail to launch.
Is there a solution for this?

**Comment by TingPing** [comment]
Not sure I understand, you mean removing that line entirely the app crashes?

**Comment by lainsce** [comment]
Yeah, that file referenced in the line is the cache of the app, where the app saves the state it's in, like how many sticky notes are present, their colors, and their contents.

**Comment by TingPing** [comment]
Well that is just a bug in notejot I suppose, it should handle it not existing. Glancing at the code it does wrap them in a `try` block.. dunno?

**Comment by lainsce** [comment]
The thing is, every time Notejot is run, it checks if the file exists, if not, it'll never save the user's notes. It would be a funny situation where the sticky notes just vanish from the borders of your monitor if you closed the session.

**Comment by TingPing** [comment]
That doesn't make any sense at all, it should always write it (writing may fail but that is unrelated).

**Comment by lainsce** [comment]
It will write it, but if the flatpak has it as ro, it'll only read it and fail to write new notes on the file, no?

**Comment by TingPing** [comment]
It shouldn't have that permission at all. `$XDG_CACHE_HOME` is set to a private directory the app has complete control over.

**Comment by lainsce** [comment]
Oh, I see. So I don't need that line altogether in the Flatpak file?
Sorry if I'm asking newbie questions, but that's what I am in making Flatpaks.

**Comment by TingPing** [comment]
> Oh, I see. So I don't need that line altogether in the Flatpak file?

Correct.

**Comment by lainsce** [comment]
I see. Fixing the issue then soon. :smile:
